version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    volumes:
      - ./server/src:/app/server/src
    restart: always
  db:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: